### ISSUE TITLE
Start exercise / end exercise formatting

### ISSUE THREAD

**Issue by nkrumm** [pcmathias/AACC-Introduction-to-R#14]
Approved format for exercises is to be:

<pre>
**Exercise**
```{r}

```
**End Exercise**
</pre>

**Comment by nkrumm** [comment]
One thought to increase readability would be to use numbered headings:

1. Overview
2. Topic
2.1 Subtopic
2.1.1 Exericse
2.2 ...

**Comment by pcmathias** [comment]
Updated lessons 01 and 03a with exercise formatting

Agree that numbered headings will be clearer but probably have to lock down content before numbering. The Markdown convention is to number will all 1's and it will auto-renumber when things are rearranged, right?

**Comment by nkrumm** [comment]
I think so, or via the YAML front matter option:
```
output: 
  html_document:
    number_sections: true
```

The problem with both of these is that it *is not any clearer in the markdown file itself*… this may just be a limitation of trying to use both compiled and uncompiled markdown...

**Comment by pcmathias** [comment]
Ok, let's continue with the Exercise and End Exercise format. Based on the experience today we may have to go through and number the exercises, then explicitly tell them what exercises to cover when we pause.

I am wondering if we also should transition to explicitly manually numbering the sections to make it easier to refer to those too.

**Comment by pcmathias** [comment]
Number exercises within each Rmd
@hermands @nkrumm @jwrudolf
