### ISSUE TITLE
Installing and Configuring

### ISSUE THREAD

**Issue by jwrudolf** [pcmathias/AACC-Introduction-to-R#16]
Patrick,

I started to pull out the installation piece into a separate file.

Expecting we will re-tread this material in class.  Thinking it may make more sense to just have a "end pre-class homework" note and direct people from readme to lesson 01 and have them work through it up to the note (then re-work it in class).

Sound okay?

Also should we expect them to get through the working directory component?

Check out line 73 in 01 where I made the note.

Joe

**Comment by pcmathias** [comment]
Yes, I think this is reasonable. I am OK getting them to the end of that Installing R section. If they can get to that point, it shouldn't be hard for them to create a folder and pick up the working directory stuff as a group.

**Comment by hermands** [comment]
Done
