### ISSUE TITLE
Handout for AACC

### ISSUE THREAD

**Issue by pcmathias** [pcmathias/AACC-Introduction-to-R#17]
@hermands @jwrudolf @nkrumm I've revised the readme and made the links visible. I knitted to pdf (with clickable links) and added the pdf to the repo.

Please review and suggest/edit before I upload to the presentation system

**Comment by jwrudolf** [comment]
Thanks for pulling this together Patrick.  This looks great!  I think it is ready to distribute.

**Comment by pcmathias** [comment]
Submitted readme pdf.
