### ISSUE TITLE
Permissions to add new branch /  write ?

### ISSUE THREAD

**Issue by hermands** [pcmathias/AACC-Introduction-to-R#2]
[hermanda@uphsvlndc106 AACC-Introduction-to-R]$ git push origin methodVal-dev 
ERROR: Permission to pcmathias/AACC-Introduction-to-R.git denied to hermands.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[hermanda@uphsvlndc106 AACC-Introduction-to-R]$ 

[hermanda@uphsvlndc106 AACC-Introduction-to-R]$ git remote -v
origin  git@github.com:pcmathias/AACC-Introduction-to-R.git (fetch)
origin  git@github.com:pcmathias/AACC-Introduction-to-R.git (push)
[hermanda@uphsvlndc106 AACC-Introduction-to-R]$

**Comment by pcmathias** [comment]
According to the collaborators page, the repo is still waiting for you to accept an invite

**Comment by pcmathias** [comment]
https://github.com/pcmathias/AACC-Introduction-to-R/invitations
