### ISSUE TITLE
Powerpoint for introducing various R-Studio panels/features?

### ISSUE THREAD

**Issue by nkrumm** [pcmathias/AACC-Introduction-to-R#5]
It may be very helpful to have a short powerpoint introducing the general features/terminology of R/Rstudy:

- Different R Studio panes and functions
- Terminal vs. Console
- R vs. Command line (if applicable)
- What are packages
- What is Markdown
- REPL vs. Chunk based vs. File evaluation

**Comment by pcmathias** [comment]
I think we should incorporate this into the intro talk/document, so people can reference it after the fact. I thought Joe was planning on covering this but we can discuss tomorrow. It'll be pretty quick to add most of this content.

**Comment by pcmathias** [comment]
@jwrudolf Something to consider for the intro document

**Comment by nkrumm** [comment]
Another thing to add: How to get help
 - how to read documentation (usage, options, examples)
 - how to google for help
 - good sources of help (SO, mailing lists, etc.)

**Comment by hermands** [comment]
Will make Rpres for 01 section
