### ISSUE TITLE
knitr output lines are prefixed with "#"

### ISSUE THREAD

**Issue by nkrumm** [pcmathias/AACC-Introduction-to-R#7]
Knitter output puts "##" before every line
![image](https://user-images.githubusercontent.com/1273758/41750732-4d483612-7572-11e8-8201-6004cc9baff1.png)

I am not sure what the standard is for this (coming from Python) but it is confusing for beginners, especially in the context of a beginner who is just learning what a code comment is.

I would propose to put specify `comment=NA` to knitr (globally).

**Comment by hermands** [comment]
Not sure if we have discussed this, but I agree.

How about we use:
knitr::opts_chunk$set(echo = TRUE, comment=NA)

Anything else to add @pcmathias @jwrudolf?

**Comment by pcmathias** [comment]
This works for me and addresses #15 as well.

**Comment by hermands** [comment]
Change convention for header in #15
